version: '3.1'

services:
  cert:
    build: ./cert
    container_name: crt
    environment:
      DO_AUTH_TOKEN: ${AUTH_TOKEN}
      DNS: ${DNS}
      EMAIL: ${EMAIL}
      DOMAINS1: ${DOMAINS1}
      DOMAINS2: ${DOMAINS2}
#    command: >
#      --path /lego
#      --dns ${DNS}
#      --email ${EMAIL}
#      --domains ${DOMAINS1}
#      --domains ${DOMAINS2}
#      --accept-tos
#      renew
#      --days 3
    volumes:
      - ./cert/accounts:/lego/accounts
      - ./cert/certificates:/lego/certificates

  web:
    image: nginx:1.18.0-alpine
    container_name: websrv
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - wp-html:/var/www/html/
    #  - ./web/html:/var/www/html
      - ./cert/certificates:/etc/nginx/cert
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/wd.conf:/etc/nginx/conf.d/wd.conf
      - ./web/logs:/var/log/nginx
      - php-fpm-socket:/var/run/php-fpm
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - cert
      - php

  php:
    container_name: phpsrv
    build: ./php
    restart: always
    volumes:
    #  - ./web/html:/var/www/html
      - ./php/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
      - php-fpm-socket:/var/run/php-fpm
      - wp-html:/var/www/html/
    depends_on:
      - blog
 
  blog:
    container_name: blogsys
    build: ./blog
    restart: always
    volumes:
      - wp-html:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      TZ: 'Asia/Tokyo'
    depends_on:
      - db

  db:
    build: ./DB
    container_name: mysql1
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      TZ: 'Asia/Tokyo'
    volumes:
      - db:/var/lib/mysql

volumes:
  wp-html:
  db:
  php-fpm-socket:
  