FROM php:8.0.0-fpm-alpine

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
    /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions @composer-2.0.8

#    https://github.com/mlocati/docker-php-extension-installer

COPY composer.json /usr/local/bin/composer.json
WORKDIR /usr/local/bin
RUN composer update
RUN composer install
WORKDIR /var/www/html

# RUN mv /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
RUN mv /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
RUN addgroup nginx
RUN adduser nginx -D -G nginx
# COPY ./setphp.ini /usr/local/etc/php/conf.d/setphp.ini

#RUN apt-get update && docker-php-ext-install mysqli pdo_mysql

# set recommended PHP.ini settings
RUN { \
   echo 'cgi.fix_pathinfo = 0'; \
   echo 'date.timezone = "Asia/Tokyo"'; \
#   echo 'extension = mysqli'; \
#  echo 'extension = pdo_mysql'; \
#  echo 'max_execution_time=-1'; \
#  echo 'memory_limit=-1'; \
#  echo 'post_max_size=-1'; \
#  echo 'upload_max_filesize=100M'; \
} > /usr/local/etc/php/conf.d/wp-recommended.ini
