FROM php:8.0.0-fpm-alpine

# Setting File
# RUN mv /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
RUN mv /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini

# Composer
#  https://getcomposer.org/download/
WORKDIR /usr/local/bin
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php --version=2.0.8
RUN php -r "unlink('composer-setup.php');"

#  https://github.com/mlocati/docker-php-extension-installer
#ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
#    /usr/local/bin/
#RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
#    install-php-extensions xdebug
#RUN install-php-extensions @composer-2.0.8

# COPY composer.json /usr/local/bin/composer.json
# RUN php composer.phar install
# WORKDIR /var/www/html

# User Add for socket
RUN addgroup nginx
RUN adduser nginx -D -G nginx
# COPY ./setphp.ini /usr/local/etc/php/conf.d/setphp.ini

# PHP extensions for wordpress core
# https://pkgs.alpinelinux.org/packages
# https://github.com/mlocati/docker-php-extension-installer
# > php -m
RUN apk upgrade --update && apk add --no-cache oniguruma libpng-dev libjpeg freetype-dev libjpeg-turbo-dev libzip-dev gettext-dev\
    && docker-php-ext-configure gd --with-freetype --with-jpeg\
    && docker-php-ext-install -j$(nproc) gd 
RUN docker-php-ext-install mysqli zip gettext opcache bcmath sockets

# set recommended PHP.ini settings
RUN { \
   echo 'cgi.fix_pathinfo = 0'; \
   echo 'date.timezone = "Asia/Tokyo"'; \
   echo 'extension = mysqli'; \
   echo 'extension = pdo_mysql'; \
   echo 'max_execution_time=-1'; \
   echo 'memory_limit=-1'; \
   echo 'post_max_size=-1'; \
   echo 'upload_max_filesize=100M'; \
} > /usr/local/etc/php/conf.d/wp-recommended.ini
